//! Instruction handlers.

pub mod initialize_protocol;
pub mod admin_pause;
pub mod admin_update_protocol;
pub mod register_collateral;
pub mod create_market;
pub mod open_user_account;
pub mod deposit;
pub mod withdraw;
pub mod open_position;
pub mod close_position;
pub mod place_trigger_order;
pub mod execute_trigger_order;
pub mod cancel_trigger_order;
pub mod liquidate;
pub mod crank_funding;
pub mod update_amm;
pub mod adapt_k;
pub mod settle_pnl;

pub use initialize_protocol::*;
pub use admin_pause::*;
pub use admin_update_protocol::*;
pub use register_collateral::*;
pub use create_market::*;
pub use open_user_account::*;
pub use deposit::*;
pub use withdraw::*;
pub use open_position::*;
pub use close_position::*;
pub use place_trigger_order::*;
pub use execute_trigger_order::*;
pub use cancel_trigger_order::*;
pub use liquidate::*;
pub use crank_funding::*;
pub use update_amm::*;
pub use adapt_k::*;
pub use settle_pnl::*;
